paths:
  /api/dish_ingredients:
    get:
      tags: [DishIngredients]
      summary: Получение списка всех ингредиентов блюд
      responses:
        200:
          description: Список ингредиентов блюд
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DishIngredient"
    post:
      tags: [DishIngredients]
      summary: Добавление нового ингредиента блюда
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DishIngredient"
      responses:
        201:
          description: Ингредиент блюда успешно добавлен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DishIngredient"

  /api/dish_ingredients/{id}:
    get:
      tags: [DishIngredients]
      summary: Получение информации об ингредиенте блюда
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Информация об ингредиенте блюда
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DishIngredient"
    put:
      tags: [DishIngredients]
      summary: Обновление информации об ингредиенте блюда
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DishIngredient"
      responses:
        200:
          description: Ингредиент блюда успешно обновлен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DishIngredient"
    delete:
      tags: [DishIngredients]
      summary: Удаление ингредиента блюда
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Ингредиент блюда успешно удален

  /api/order_items:
    get:
      tags: [OrderItems]
      summary: Получение списка всех пунктов заказа
      responses:
        200:
          description: Список пунктов заказа
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderItem"
    post:
      tags: [OrderItems]
      summary: Добавление нового пункта заказа
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderItem"
      responses:
        201:
          description: Пункт заказа успешно добавлен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderItem"

  /api/order_items/{id}:
    get:
      tags: [OrderItems]
      summary: Получение информации о пункте заказа
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Информация о пункте заказа
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderItem"
    put:
      tags: [OrderItems]
      summary: Обновление информации о пункте заказа
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderItem"
      responses:
        200:
          description: Пункт заказа успешно обновлен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderItem"
    delete:
      tags: [OrderItems]
      summary: Удаление пункта заказа
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Пункт заказа успешно удален
